# Generated by Django 5.1.7 on 2025-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BRANCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chi_nhanh', models.CharField(max_length=255, verbose_name='Tên chi nhánh')),
                ('dia_chi', models.TextField(verbose_name='Địa chỉ')),
                ('kinh_do', models.FloatField(verbose_name='Kinh độ')),
                ('vi_do', models.FloatField(verbose_name='Vĩ độ')),
                ('gio_mo_cua', models.TimeField(blank=True, null=True, verbose_name='Giờ mở cửa')),
                ('gio_dong_cua', models.TimeField(blank=True, null=True, verbose_name='Giờ đóng cửa')),
                ('tinh_trang', models.BooleanField(default=False, verbose_name='Tình trạng có ATM (Có/Không)')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='branch_images/', verbose_name='Hình ảnh')),
            ],
        ),
    ]
